apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app
  namespace: cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
    template:
      metadata:
        labels:
          app: cicd-demo
      spec:
        containers:
        - name: cicd-demo
          image: ${DOCKER_USERNAME}/cicd-demo-app:${VERSION}
          env:
          - name: VERSION
            value: "${VERSION}"
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: "0.2"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20